import React, {useEffect} from "react";
import "./App.css";
import * as s from "./styles/globalStyles";
import nEggLogo from "./images/nEggLogoTitle.png";
import discord from "./images/discord.png";
import twitter from "./images/twitter.png";

function App() {
  useEffect(() => {
    document.title = "nAnimals 🐻🐱🐶🐰"
  }, []);

  return (
    <s.Screen>
      <s.Container>
        <s.SpacerLarge />
          <s.Row>
            <s.Column>
              <a href="https://discord.gg/CaC2wAxtyh" target="_blank" rel="noopener noreferrer">
              <img src={discord} height={50} width={50} alt="discord"/>
              </a>
            </s.Column>
            <s.SpacerSmall />
            <s.Column>
              <a href="https://www.twitter.com/nanimalsfun" target="_blank" rel="noopener noreferrer">
              <img src={twitter} height={50} width={50} alt="twitter"/>
              </a>
            </s.Column>
          </s.Row>
          <img src={nEggLogo} height={600} width={600} alt="nEgg Logo"/>
          <s.SpacerLarge />
          <s.TextTitle>COMING SOON!</s.TextTitle>
        </s.Container>
        <s.Container>
          <s.SpacerLarge />
          <s.TextDescription>COPYRIGHT 2021 SEAN BETTS</s.TextDescription>
          <s.SpacerSmall />
          <s.TextDescription>CONTRACT: xxxxxxxxxxxxxxx</s.TextDescription>
          <s.SpacerLarge />
            <s.NFTContainerBar>
        <s.SpacerLarge />
        <s.TextTitle2>ABOUT</s.TextTitle2>
          <s.SpacerXSmall />
          <s.TextDescription3>nANIMALs is a new generative NFT art project living on the Ethereum-compatible Polygon Proof of Stake (POS) Network.</s.TextDescription3>
          <s.SpacerSmall />
          <s.TextDescription3>Our ambition for this project is not to take ourselves too seriously and to just enjoy the space. We're looking to build a relaxed community on Discord to hang out and there will be lots of fun to be had along the way!</s.TextDescription3>
          <s.SpacerSmall />
          <s.TextDescription3>Love & hugs,</s.TextDescription3>
          <s.SpacerSmall />
          <s.TextDescription3><span role="img" aria-labelledby="panda">🐼</span>│ MOTHER</s.TextDescription3>
          <s.SpacerLarge />
        </s.NFTContainerBar>
        <s.SpacerLarge />
        <s.NFTContainerBar>
        <s.SpacerLarge />
        <s.TextTitle2>WHAT IS IT?</s.TextTitle2>
          <s.SpacerXSmall />
          <s.TextDescription3>Every nANIMAL starts off as a nEGG. On hatching from it's nEGG, each nANIMAL is autogenerated from over 50+ intial features and is completely unique.</s.TextDescription3>
          <s.SpacerXSmall />
          <s.TextDescription3>Each nEGG and nANIMAL exists as an ERC-721 token on polygon, is hosted on IPFS, with an initial mint cost of 2 MATIC for each nEGG and an initial hatching cost of 2 MATIC for each nANIMAL.</s.TextDescription3>
          <s.SpacerXSmall />
          <s.TextDescription3>Holding a nEGG/nANIMAL grants you copyright and commercial usage, as well as access to future airdrops.</s.TextDescription3>
          <s.SpacerLarge />
        </s.NFTContainerBar>
        <s.SpacerLarge />
        <s.NFTContainerBar>
        <s.SpacerLarge />
          <s.TextTitle2>ROADMAP</s.TextTitle2>
          <s.SpacerXSmall />
          <s.TextSubTitle3>STEP 1</s.TextSubTitle3>
          <s.TextDescription3>We will be releasing {data.maxMintSupply} nEGGs to be minted. The minting cost will be {data.mintPrice/1000000000000000000} MATIC per nEGG and there will be a maximum mint of {data.maxMintQuantity} nEGGs per wallet</s.TextDescription3>
          <s.SpacerLarge />
          <s.TextSubTitle3>STEP 2</s.TextSubTitle3>
          <s.TextDescription3>Once all {data.maxMintSupply} nEGGs have been minted, the countdown will begin for the hatching of the 1st generation of nANIMALs. All original minters of nEggs will be given the "<span role="img" aria-labelledby="egg">🥚</span>│OG nEGG" role and have exclusive access to new channels on the Discord server.</s.TextDescription3>
           <s.SpacerLarge />
          <s.TextSubTitle3>STEP 3</s.TextSubTitle3>
          <s.TextDescription3>Once the countdown is over it's Hatching Time! Hatching 1 nEGG will cost {data.mintPrice/1000000000000000000} MATIC and will hatch 1 nANIMAL.</s.TextDescription3>
          <s.SpacerXSmall />
          <s.TextDescription3>Every nANIMAL holder will be given the "<span role="img" aria-labelledby="berar">🐻</span>│nANIMAL" role and have access to new channels on the Discord server. Every generation of nANIMALs will have their own exclusive role and collection of channels on Discord that only owners of that generation will have access to.</s.TextDescription3>
          <s.SpacerXSmall />
          <s.TextDescription3>Each nEGG will be able to be re-hatched for future generations of nANIMALs. However, watch out - 5% of nANIMALs will die on hatching! (but the original nEGG will remain intact).</s.TextDescription3>
          <s.SpacerLarge />
          <s.TextSubTitle3>STEP 4</s.TextSubTitle3>
          <s.TextDescription3>When hatching ends for Generation 1, the countdown will begin for the hatching of the 2nd Generation of nANIMALs and the cycle will continue!</s.TextDescription3>
          <s.SpacerLarge />
        </s.NFTContainerBar>
        <s.Container>
          <s.SpacerLarge />
          <s.TextDescription>COPYRIGHT 2021 SEAN BETTS</s.TextDescription>
          <s.SpacerSmall />
          <s.TextDescription>CONTRACT ADDRESS: {data.contractAddress}</s.TextDescription>
          <s.SpacerLarge />
        </s.Container>
    </s.Screen>
  );
}

export default App;
